name: my_secure_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  http: ^1.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  mocktail: ^1.0.4

  # Firebase dependencies
  firebase_core: ^2.32.0
  firebase_auth: ^4.8.0
  add_2_calendar: ^3.0.1
  url_launcher: ^6.3.2
  flutter_riverpod: ^3.2.1
  google_fonts: ^8.0.1
  provider: ^6.1.5+1
  google_maps_flutter: ^2.14.2
  cloud_firestore: ^4.17.5
  connectivity_plus: ^7.0.0
  image_picker: ^1.2.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
